AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 96

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/FileName:
  Enabled: false
  Exclude:
    - bin/_guard-core

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
